import {Geist, Geist_Mono, Montserrat, Outfit, Inter} from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
    subsets: ["latin", "cyrillic"]
});

const montserrat = Montserrat({
    variable: "--font-montserrat",
    subsets: ["latin", "cyrillic"]
})

const outfit = Outfit({
    variable: "--font-outfit",
    subsets: ["latin", "cyrillic"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

    return (
    <html lang="ru" className="dark:scheme-dark">
    <body className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${outfit.variable} ${inter.variable} antialiased`}>
        <Header/>
        {children}
        <Footer/>
    </body>
    </html>
  );
}
