import Image from "next/image";

export default function Home() {
  return (
    <div className="font-sans grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20">
      <main className="flex flex-col gap-[32px] row-start-2 items-center sm:items-start">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad aliquid at beatae corporis culpa delectus dolorem doloremque ea error eveniet excepturi expedita explicabo facilis fugiat harum incidunt laboriosam libero minus modi natus necessitatibus non numquam, odio officia optio quae, quasi quia quibusdam ratione repudiandae saepe sed sequi similique sint tenetur vel voluptatem. Alias assumenda culpa distinctio exercitationem inventore ipsam quam veritatis. Aliquam asperiores consectetur consequatur cupiditate deserunt eos error ex expedita fuga fugiat harum in iste itaque iusto laudantium magnam molestiae provident quidem quo quos reiciendis rem reprehenderit, tempora voluptate voluptates? Ad, cum iusto nulla odit reiciendis similique sunt!</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad aliquid at beatae corporis culpa delectus dolorem doloremque ea error eveniet excepturi expedita explicabo facilis fugiat harum incidunt laboriosam libero minus modi natus necessitatibus non numquam, odio officia optio quae, quasi quia quibusdam ratione repudiandae saepe sed sequi similique sint tenetur vel voluptatem. Alias assumenda culpa distinctio exercitationem inventore ipsam quam veritatis. Aliquam asperiores consectetur consequatur cupiditate deserunt eos error ex expedita fuga fugiat harum in iste itaque iusto laudantium magnam molestiae provident quidem quo quos reiciendis rem reprehenderit, tempora voluptate voluptates? Ad, cum iusto nulla odit reiciendis similique sunt!</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad aliquid at beatae corporis culpa delectus dolorem doloremque ea error eveniet excepturi expedita explicabo facilis fugiat harum incidunt laboriosam libero minus modi natus necessitatibus non numquam, odio officia optio quae, quasi quia quibusdam ratione repudiandae saepe sed sequi similique sint tenetur vel voluptatem. Alias assumenda culpa distinctio exercitationem inventore ipsam quam veritatis. Aliquam asperiores consectetur consequatur cupiditate deserunt eos error ex expedita fuga fugiat harum in iste itaque iusto laudantium magnam molestiae provident quidem quo quos reiciendis rem reprehenderit, tempora voluptate voluptates? Ad, cum iusto nulla odit reiciendis similique sunt!</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad aliquid at beatae corporis culpa delectus dolorem doloremque ea error eveniet excepturi expedita explicabo facilis fugiat harum incidunt laboriosam libero minus modi natus necessitatibus non numquam, odio officia optio quae, quasi quia quibusdam ratione repudiandae saepe sed sequi similique sint tenetur vel voluptatem. Alias assumenda culpa distinctio exercitationem inventore ipsam quam veritatis. Aliquam asperiores consectetur consequatur cupiditate deserunt eos error ex expedita fuga fugiat harum in iste itaque iusto laudantium magnam molestiae provident quidem quo quos reiciendis rem reprehenderit, tempora voluptate voluptates? Ad, cum iusto nulla odit reiciendis similique sunt!</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad aliquid at beatae corporis culpa delectus dolorem doloremque ea error eveniet excepturi expedita explicabo facilis fugiat harum incidunt laboriosam libero minus modi natus necessitatibus non numquam, odio officia optio quae, quasi quia quibusdam ratione repudiandae saepe sed sequi similique sint tenetur vel voluptatem. Alias assumenda culpa distinctio exercitationem inventore ipsam quam veritatis. Aliquam asperiores consectetur consequatur cupiditate deserunt eos error ex expedita fuga fugiat harum in iste itaque iusto laudantium magnam molestiae provident quidem quo quos reiciendis rem reprehenderit, tempora voluptate voluptates? Ad, cum iusto nulla odit reiciendis similique sunt!</p>
      </main>
    </div>
  );
}
